; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Sun Dec 19 2021 00:16:06 GMT+0300 (Москва, стандартное время)
M104 S0
M140 S0
M106 S0
M84
