; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.0-LPC-STM32+10 on Sun Dec 19 2021 00:16:06 GMT+0300 (Москва, стандартное время)
; Wait for set temperatures to be reached
M116 P0

